"""Kick off an autonomous selfplay/train pipeline run on Narval.

Terminology: a pipeline **cycle** is one selfplay round followed by one
training pass on the accumulated replay buffer. Cycle 0 is pretrain-only
(bootstrap data, no selfplay). Cycles 1..N each produce a new dataset dir
and a new checkpoint. "epoch" inside train_offline.py means one pass
through the loaded replay buffer — distinct from pipeline cycles.

Creates the pipeline directory, freezes the config, and submits the first
SLURM job. Subsequent jobs are chained via the submit-next (A2) pattern
inside slurm/pipeline_train.sh.

Usage (v3a random-board example):
  python pipeline_kickoff.py \
    --pipeline_root=/scratch/huang651/grid_mcts2/pipelines \
    --bootstrap_data=/scratch/huang651/grid_mcts2/datasets/wave03a_rnd_plancost \
    --cycles=5 \
    --pretrain_epochs=2 --train_epochs=2 \
    --sliding_window=5 \
    --num_tasks=20 --games_per_task=1000 \
    --selfplay_time=06:00:00 --train_time=01:00:00 \
    --preset=hpc \
    --config_override=map_num=2 \
    --config_override=random_board=True \
    --config_override=mcts.num_simulations=10000 \
    --config_override=env.reward_mode=plan_cost \
    --config_override=training.buffer_size=1000000
"""

import argparse
import hashlib
import json
import os
import shlex
import subprocess
import sys
import time

from neutral_atoms.pipeline import append_event, write_state


REPO_ROOT = os.path.dirname(os.path.abspath(__file__))


def _new_pipeline_id():
    return hashlib.sha1(
        f'{time.time()}_{os.uname().nodename}'.encode()
    ).hexdigest()[:8]


def _write_pipeline_params(pipeline_dir, args, pipeline_id, final_cycle, config_flags_str):
    """Bash-sourceable file that every SLURM job reads for pipeline state."""
    path = os.path.join(pipeline_dir, 'pipeline_params.sh')
    params = {
        'PIPELINE_ID': pipeline_id,
        'PIPELINE_DIR': pipeline_dir,
        'REPO_ROOT': REPO_ROOT,
        'FINAL_CYCLE': str(final_cycle),
        'NUM_TASKS': str(args.num_tasks),
        'GAMES_PER_TASK': str(args.games_per_task),
        'PRETRAIN_EPOCHS': str(args.pretrain_epochs),
        'TRAIN_EPOCHS': str(args.train_epochs),
        'SLIDING_WINDOW': str(args.sliding_window),
        'BOOTSTRAP_DATA': args.bootstrap_data or '',
        'SELFPLAY_TIME': args.selfplay_time,
        'TRAIN_TIME': args.train_time,
        'SELFPLAY_MEM': args.selfplay_mem,
        'SELFPLAY_CPUS': str(args.selfplay_cpus),
        'SELFPLAY_NUM_WORKERS': str(args.selfplay_num_workers),
        'SELFPLAY_GRES': args.selfplay_gres,
        'TRAIN_MEM': args.train_mem,
        'SLURM_ACCOUNT': args.slurm_account,
        'PRESET': args.preset,
        'CONFIG_FLAGS': config_flags_str,
    }
    with open(path, 'w') as f:
        f.write('# Auto-generated by pipeline_kickoff.py. Frozen for this pipeline run.\n')
        for k, v in params.items():
            f.write(f'{k}={shlex.quote(v)}\n')
    return path


def _freeze_config(pipeline_dir, args, pipeline_id):
    """Human-readable snapshot of the pipeline's full settings."""
    path = os.path.join(pipeline_dir, 'config.json')
    snapshot = {
        'pipeline_id': pipeline_id,
        'created_at': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'bootstrap_data': args.bootstrap_data,
        'bootstrap_ckpt': args.bootstrap_ckpt or None,
        'cycles': args.cycles,
        'pretrain_epochs': args.pretrain_epochs,
        'train_epochs': args.train_epochs,
        'num_tasks': args.num_tasks,
        'games_per_task': args.games_per_task,
        'sliding_window': args.sliding_window,
        'preset': args.preset,
        'config_overrides': args.config_override,
        'slurm': {
            'account': args.slurm_account,
            'selfplay_time': args.selfplay_time,
            'selfplay_cpus': args.selfplay_cpus,
            'selfplay_mem': args.selfplay_mem,
            'train_time': args.train_time,
            'train_mem': args.train_mem,
        },
        'notes': args.notes,
    }
    with open(path, 'w') as f:
        json.dump(snapshot, f, indent=2)
    return path


def _submit_pretrain(pipeline_dir, pipeline_id, slurm_account, train_time, train_mem):
    """Submit cycle-0 train (pretrain on bootstrap data) with no dependency."""
    env = os.environ.copy()
    env['PIPELINE_DIR'] = pipeline_dir
    env['CYCLE'] = '0'
    env['PIPELINE_PHASE'] = 'pretrain'
    script = os.path.join(REPO_ROOT, 'slurm', 'pipeline_train.sh')
    result = subprocess.run(
        ['sbatch', '--parsable',
         f'--account={slurm_account}',
         f'--time={train_time}',
         f'--mem={train_mem}',
         f'--job-name=pipe_tr_{pipeline_id}_c00',
         f'--output=slurm/logs/pipe_tr_{pipeline_id}_c00_%j.out',
         script], env=env,
        check=True, capture_output=True, text=True,
    )
    job_id = result.stdout.strip().split(';')[0]
    append_event(pipeline_dir, 'cycle_00_pretrain_launched',
                 pipeline_id=pipeline_id, slurm_job_id=job_id)
    return job_id


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--pipeline_root', required=True,
                   help='Parent dir where pipeline_<id>/ will be created.')
    p.add_argument('--pipeline_id', default='',
                   help='Override auto-generated id. Must not collide.')
    p.add_argument('--bootstrap_data', default='',
                   help='Existing dataset dir to pretrain on (cycle 0). '
                        'If empty, cycle 0 is a selfplay cycle (not yet supported).')
    p.add_argument('--bootstrap_ckpt', default='',
                   help='Prior-pipeline ckpt to warm-start from (stamped as parent_run). '
                        'If empty, random init.')
    p.add_argument('--cycles', type=int, required=True,
                   help='Number of selfplay+train cycles AFTER pretrain. '
                        'Total train jobs = cycles + 1 if bootstrap_data is set.')
    p.add_argument('--pretrain_epochs', type=float, default=2.0,
                   help='Number of passes through bootstrap data during pretrain.')
    p.add_argument('--train_epochs', type=float, default=2.0,
                   help='Number of passes through the sliding-window replay buffer '
                        'per cycle train step.')
    p.add_argument('--num_tasks', type=int, default=20)
    p.add_argument('--games_per_task', type=int, default=1000)
    p.add_argument('--sliding_window', type=int, default=5,
                   help='K = number of most-recent dataset dirs included in training.')
    p.add_argument('--preset', choices=['default', 'hpc'], default='hpc')
    p.add_argument('--config_override', action='append', default=[],
                   help='Repeated, e.g. --config_override=mcts.num_simulations=10000')
    p.add_argument('--slurm_account', default='rrg-aspuru')
    p.add_argument('--selfplay_time', default='06:00:00')
    p.add_argument('--selfplay_cpus', type=int, default=64)
    p.add_argument('--selfplay_num_workers', type=int, default=0,
                   help='Parallel MCTS workers per task. 0 = selfplay_cpus-2 (legacy).')
    p.add_argument('--selfplay_gres', default='',
                   help='SLURM --gres for selfplay tasks, e.g. "gpu:1". Empty = CPU only.')
    p.add_argument('--selfplay_mem', default='32G')
    p.add_argument('--train_time', default='01:00:00')
    p.add_argument('--train_mem', default='32G')
    p.add_argument('--notes', default='')
    args = p.parse_args()

    if not args.bootstrap_data and args.cycles < 1:
        sys.exit('Need at least --bootstrap_data or --cycles>=1 for any work.')
    if args.selfplay_num_workers == 0:
        args.selfplay_num_workers = args.selfplay_cpus - 2

    pipeline_id = args.pipeline_id or _new_pipeline_id()
    pipeline_dir = os.path.abspath(os.path.join(args.pipeline_root, f'pipeline_{pipeline_id}'))
    if os.path.exists(pipeline_dir):
        sys.exit(f'Pipeline dir already exists: {pipeline_dir}')
    os.makedirs(pipeline_dir)
    os.makedirs(os.path.join(pipeline_dir, 'checkpoints'))
    os.makedirs(os.path.join(pipeline_dir, 'logs'))

    config_flags_str = ' '.join(f'--config.{o}' for o in args.config_override)

    # final_cycle is the index of the last train cycle. With bootstrap_data:
    #   cycle 0 = pretrain, cycles 1..N = selfplay+train pairs => final_cycle = cycles
    # Without bootstrap (not yet supported):
    #   cycles 0..N-1 => final_cycle = cycles - 1
    if args.bootstrap_data:
        final_cycle = args.cycles
    else:
        final_cycle = args.cycles - 1

    _write_pipeline_params(pipeline_dir, args, pipeline_id, final_cycle, config_flags_str)
    _freeze_config(pipeline_dir, args, pipeline_id)

    append_event(pipeline_dir, 'pipeline_started',
                 pipeline_id=pipeline_id,
                 bootstrap_data=args.bootstrap_data,
                 bootstrap_ckpt=args.bootstrap_ckpt,
                 cycles=args.cycles,
                 final_cycle=final_cycle)
    write_state(pipeline_dir)

    print(f'Pipeline: {pipeline_id}')
    print(f'  dir:    {pipeline_dir}')
    print(f'  cycles: {args.cycles} (final_cycle={final_cycle})')
    print(f'  pretrain_epochs={args.pretrain_epochs}  train_epochs={args.train_epochs}')
    print(f'  sliding_window={args.sliding_window}')
    print(f'  preset: {args.preset}')
    if args.config_override:
        print(f'  config overrides:')
        for o in args.config_override:
            print(f'    --config.{o}')

    if args.bootstrap_data:
        job_id = _submit_pretrain(pipeline_dir, pipeline_id,
                                  args.slurm_account, args.train_time, args.train_mem)
        print(f'Submitted cycle_00 pretrain: slurm_job_id={job_id}')
    else:
        sys.exit('Kickoff without --bootstrap_data not yet supported.')

    write_state(pipeline_dir)
    print(f'State: {os.path.join(pipeline_dir, "state.json")}')
    print(f'Events: {os.path.join(pipeline_dir, "events.jsonl")}')


if __name__ == '__main__':
    main()
